# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_fivetran_logs'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_fivetran_logs:
    # Staging models
    staging:
      +materialized: view
      +schema: stg_fivetran_log
    
    # Intermediate models
    intermediate:
      +materialized: view
      +schema: int_fivetran_log
    
    # Mart models
    marts:
      +materialized: table
      +schema: fct_fivetran_logs
      
      # Specific mart areas
      usage:
        +tags: ['usage', 'reporting']
      performance:
        +tags: ['performance', 'reporting']
      monitoring:
        +tags: ['monitoring', 'reporting']
      governance:
        +tags: ['governance', 'reporting']
        
    # Keep the example folder configuration
    example:
      +materialized: table